### ISSUE TITLE
Nice work~

### ISSUE THREAD

**Issue by BlueBlueFF** [RayRuiboChen/Self-Filter#1]
1. Do you have tried using llava-665K, whick is more robust than 158K dataset?
2. When will you release the pretrain score net?
Thanks~

**Comment by RayRuiboChen** [comment]
We do plan to test our method on LLaVA 1.5 recently, which uses the 665K dataset. 
The code and pre-trained score net will be released within the next two weeks. 
Thank you.

**Comment by whitesockcat** [comment]
> We do plan to test our method on LLaVA 1.5 recently, which uses the 665K dataset. The code and pre-trained score net will be released within the next two weeks. Thank you.

Have there been any developments or advancements?
We have observed that for a dataset of around 665k instances, random selection seems to be a quite effective approach.

**Comment by RayRuiboChen** [comment]
We do not have a thorough exploration of the 665k dataset so we did not publish the results. However, in my experiments for 665k instances, random selection does not perform well, and our method can produce better results. Maybe you could check your implementation?
